using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace DotAutoDocConfig.SourceGenerator.Tests;

public class SourceGeneratorWithAttributesTests
{
    private const string VectorClassText = @"
namespace TestNamespace;

[Generators.Report]
public partial class Vector3
{
    public float X { get; set; }
    public float Y { get; set; }
    public float Z { get; set; }
}";

    private const string ExpectedGeneratedClassText = @"// <auto-generated/>

using System;
using System.Collections.Generic;

namespace TestNamespace;

partial class Vector3
{
    public IEnumerable<string> Report()
    {
        yield return $""X:{this.X}"";
        yield return $""Y:{this.Y}"";
        yield return $""Z:{this.Z}"";
    }
}
";

    [Test]
    public async Task GenerateReportMethod()
    {
        // Create an instance of the source generator.
        SourceGeneratorWithAttributes generator = new();

        // Source generators should be tested using 'GeneratorDriver'.
        CSharpGeneratorDriver driver = CSharpGeneratorDriver.Create(generator);

        // We need to create a compilation with the required source code.
        CSharpCompilation compilation = CSharpCompilation.Create(nameof(SourceGeneratorWithAdditionalFilesTests),
            [CSharpSyntaxTree.ParseText(VectorClassText)],
            [
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            ]);

        // Run generators and retrieve all results.
        GeneratorDriverRunResult runResult = driver.RunGenerators(compilation).GetRunResult();

        // All generated files can be found in 'RunResults.GeneratedTrees'.
        SyntaxTree generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("Vector3.g.cs"));

        // Complex generators should be tested using text comparison.
        await Assert.That((await generatedFileSyntax.GetTextAsync()).ToString()).IsEqualTo(ExpectedGeneratedClassText);
    }
}
